### ISSUE TITLE
Clarify usage without image

### ISSUE THREAD

**Issue by Khartir** [hypriot/flash#141]
Both the readme and the usage state:

> If no image is specified, the script will try to configure an existing image. This is useful to try several configuration without the need to rewrite the image every time.

However it is not at all clear how this works. Running `./flash -u user-data` only prints the usage. I assume that this only works with specific options? If so, it would be nice if these are mentioned.

**Comment by StefanScherer** [comment]
Oh I think user-data file is interpreted only once on first boot. With occi and device-init it was possible to reconfigure hostname etc.

**Comment by hannonq** [comment]
@StefanScherer does that mean that it's no longer possible to make changes without rewriting the images?

Or can I just copy the files manually to /boot/device-init.yaml?

**Comment by StefanScherer** [comment]
@hannonq We no longer install device-init, so copying the yaml to /boot doesn’t help.

**Comment by manicmonkey** [comment]
Due to the way cloud-init works I think there are some 'instance' related files that would need to be removed from the card to retrigger some of the per-instance modules (such as write_files).

Looks like the 'just update the config' functionality was removed quite some time ago: https://github.com/hypriot/flash/commit/19552a2e7a6e9e277aeb2e88edd24d3ec96a6ead
